# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'Default'

steps:
  - script: echo "Setting up Python environment"
    displayName: 'Setup Environment'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
  - script: |
      python -m venv env
      source env/bin/activate
      pip install -r requirements.txt || echo "No dependencies to install"
    displayName: 'Install dependencies'
  - script: echo "Running tests (if any)"
    displayName: 'Run Tests'
